FROM oven/bun:alpine AS base

WORKDIR /app

# Install dependencies with bun
FROM base AS deps

COPY package.json bun.lock* ./
RUN bun install --no-save --frozen-lockfile

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app

# Build arguments
ARG API_ENDPOINT
ARG NEXT_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NODE_ENV
# Set as environment variables for the build process
ENV NODE_ENV=${NODE_ENV}
ENV API_ENDPOINT=${API_ENDPOINT}
ENV NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["bun", "./server.js"]
