FROM oven/bun:alpine AS base

WORKDIR /app

# Install dependencies with bun
FROM base AS deps

COPY package.json bun.lock* ./
COPY src/prisma/schema.prisma ./src/prisma/schema.prisma
COPY prisma.config.ts ./prisma.config.ts
RUN bun install --no-save --frozen-lockfile
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
RUN NODE_ENV=${NODE_ENV} bun run prisma:generate

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app

# Build arguments
ARG NODE_ENV
ARG DATABASE_URL
ENV NODE_ENV=${NODE_ENV}
ENV DATABASE_URL=${DATABASE_URL}

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/src/prisma/generated ./src/prisma/generated
COPY . .
RUN NODE_ENV=${NODE_ENV} bun run build

# Production image, copy all the files and start the server
FROM base AS runner
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src/prisma/generated ./src/prisma/generated
COPY --from=builder /app/tsconfig.json ./tsconfig.json
ARG NODE_ENV
ARG PORT
ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}

EXPOSE ${PORT}
CMD ["bun", "run", "./dist/src/server.js"]
